### ISSUE TITLE
"c_fsevents.o: No such file or directory" build error with GHC 9.8

### ISSUE THREAD

**Issue by simonmichael** [luite/hfsevents#16]
hfsevents builds for me with GHC 9.6 but not with 9.8. Would anyone have ideas on this error ?

```
$ stack build hfsevents --stack-yaml stack9.8.yaml

Warning: Stack has not been tested with GHC versions 9.8 and above, and using 9.8.1, this may fail.
hfsevents> configure
hfsevents> Configuring hfsevents-0.1.6...
hfsevents> build
hfsevents> Preprocessing library for hfsevents-0.1.6..
hfsevents> Building library for hfsevents-0.1.6..
hfsevents> [1 of 1] Compiling System.OSX.FSEvents
hfsevents> ar: .stack-work/dist/aarch64-osx/ghc-9.8.1/build/cbits/c_fsevents.o: No such file or directory

Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       [S-7011]
       While building package hfsevents-0.1.6 (scroll up to its section to see the error) using:
       /Users/simon/.stack/setup-exe-cache/aarch64-osx/Cabal-simple_6HauvNHV_3.10.2.0_ghc-9.8.1 --verbose=1 --builddir=.stack-work/dist/aarch64-osx/ghc-9.8.1 build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1 
```

**Comment by luite** [comment]
Which cabal version are you using? It doesn't appear to fail on my system (macOS 14.2.1):
```
cabal-install version 3.10.2.0
compiled using version 3.10.2.1 of the Cabal library 
```

**Comment by simonmichael** [comment]
I'm using stack as mentioned. Unfortunately I wasn't smart enough to figure out how to force cabal-install to (re)install the package.

**Comment by luite** [comment]
Maybe I can reproduce it with stack. What's the `stack9.8.yaml` file you're using?

**Comment by simonmichael** [comment]
It was this:
```
resolver: nightly-2024-01-04

packages:
- hledger-lib
- hledger
# blocked by https://github.com/luite/hfsevents/issues/16
#- hledger-ui
- hledger-web

extra-deps:
- cassava-megaparsec-2.1.0
- email-validate-2.3.2.19
- yesod-1.6.2.1
- yesod-form-1.7.6

# work around https://github.com/stackbuilders/cassava-megaparsec/issues/39
allow-newer: true

nix:
  pure: false
  packages: [perl gmp ncurses zlib]

ghc-options:
  # silence 9.8's new partial warnings for now
  "$locals": -Wno-x-partial
```
